### **Axis with array**

In [2]:
import numpy as np

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 9, 8]])

In [12]:
arr.sum()

45

In [14]:
arr.sum(axis=0)

array([12, 15, 18])

In [15]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [20]:
arr.max(axis=0)

array([7, 8, 9])

In [22]:
arr.min(axis=1)

array([1, 4, 7])

In [26]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [27]:
arr.ndim

2

In [63]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 9, 8]])

In [67]:
np.where(arr>2)

(array([0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [71]:
np.count_nonzero(arr)

9

In [72]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

**All arg method return index**

In [32]:
arr.argmax()

7

In [37]:
arr.argmax()

7

In [34]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 2, 1]], dtype=int64)

In [40]:
arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [53]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 2, 1]], dtype=int64)

In [52]:
list1 = np.array([1, 2])
list2 = np.array([3, 4])
list1 - list2 # similarly can do addition, multiplication, division

array([-2, -2])